# Basic exercise on Arrays, Matrices

In [1]:
import numpy as np

## Arrays

In [2]:
# 1. Create an array of integers from 0 to 9
m = np.array(range(10))
n = np.arange(10)
print('m',m,'\nn',n)

m [0 1 2 3 4 5 6 7 8 9] 
n [0 1 2 3 4 5 6 7 8 9]


In [3]:
# 2. Retrieve the first 5 elements
n[:5]

array([0, 1, 2, 3, 4])

In [4]:
# 3. Retrieve elements after 5
n[6:]

array([6, 7, 8, 9])

In [5]:
# 4. Retrieve elements from 4 to 7
n[4:8]

array([4, 5, 6, 7])

In [6]:
# 5. Retrieve the even numbers
n[::2]

array([0, 2, 4, 6, 8])

In [7]:
# 6. Retrieve the odd numbers (without zero)
n[1::2]

array([1, 3, 5, 7, 9])

In [8]:
# 7. The last three elements
n[-3:]

array([7, 8, 9])

In [9]:
# 8. Items in reverse order
n[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
# 9. Top 5 in reverse order
n[4::-1]

array([4, 3, 2, 1, 0])

In [11]:
# 10. Select all with slicing syntax
n[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## n-dimensional Matrix

In [12]:
# 1. Generate a matrix in the reverse direction
n = np.ndarray(shape=(3,3), dtype=int, buffer=np.arange(9,0,-1))
n

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [13]:
b = np.arange(9,0,-1).reshape(3,3)

In [14]:
# 2. Create a vector
b[:,0]

array([9, 6, 3])

In [15]:
# 3. Create a column vector
b[:,0,np.newaxis]

array([[9],
       [6],
       [3]])

In [16]:
# 4. Retrieve the last 2 columns
b[:,1:]

array([[8, 7],
       [5, 4],
       [2, 1]])

In [17]:
# 5. Retrieving a sub-matrix
b[:2,:2]

array([[9, 8],
       [6, 5]])

In [18]:
# 6. Reorder matrix
b[::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

## Shallow VS Deep copy

In [19]:
x1 = np.arange(10,100,10).reshape(3,3)
x2 = x1[1:,1:]
x2[0,0]=99
print('x2:\n',x2)
print('x1:\n',x1)
#=> 99! shallow copy

x2:
 [[99 60]
 [80 90]]
x1:
 [[10 20 30]
 [40 99 60]
 [70 80 90]]


In [20]:
x1 = np.arange(10,100,10).reshape(3,3)
x2 = np.copy(x1[1:,1:])
x2[0,0]=99
print('x2:\n',x2)
print('x1:\n',x1)
#=>  deep copy

x2:
 [[99 60]
 [80 90]]
x1:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
